use serde::Serialize;
use serde_json::json;

#[derive(Debug, Clone, Serialize)]
pub struct AgentProfileFieldReference {
    pub path: &'static str,
    pub required: bool,
    pub allowed_values: Vec<&'static str>,
    pub example: serde_json::Value,
    pub description: &'static str,
}

pub fn agent_profile_field_reference() -> Vec<AgentProfileFieldReference> {
    vec![
        field(
            "schema_version",
            true,
            vec!["1"],
            json!(1),
            "Profile schema version.",
        ),
        field(
            "name",
            true,
            vec!["[a-zA-Z0-9][a-zA-Z0-9._-]*"],
            json!("claude-ds"),
            "Profile name used by --agent.",
        ),
        field(
            "kind",
            true,
            vec![
                "codex",
                "claude-code",
                "opencode",
                "pi-coding-agent",
                "custom",
                "fake",
            ],
            json!("claude-code"),
            "CLI harness kind.",
        ),
        field(
            "display_name",
            true,
            vec!["string"],
            json!("Claude DS"),
            "Human-readable report name.",
        ),
        field(
            "command",
            true,
            vec!["shell command"],
            json!("claude-ds -p --bare --output-format text"),
            "Agent command template.",
        ),
        field(
            "input_mode",
            true,
            vec!["argument", "file", "stdin", "tty"],
            json!("stdin"),
            "How the task instruction is passed to the agent.",
        ),
        field(
            "working_dir",
            true,
            vec!["workspace", "run_dir"],
            json!("workspace"),
            "Agent working directory.",
        ),
        field(
            "timeout_sec",
            true,
            vec!["positive integer"],
            json!(300),
            "Default per-task agent timeout.",
        ),
        field(
            "auth.inherit",
            true,
            vec!["true", "false"],
            json!(true),
            "Enable declared auth env/path inheritance.",
        ),
        field(
            "auth.inherit_env",
            true,
            vec!["string[]"],
            json!(["ANTHROPIC_AUTH_TOKEN"]),
            "Environment variable names to pass through.",
        ),
        field(
            "auth.include_paths",
            true,
            vec!["path[]", "host:container:mode[]"],
            json!([]),
            "Auth/config paths to mount.",
        ),
        field(
            "auth.exclude_paths",
            true,
            vec!["path[]"],
            json!([]),
            "Inherited auth paths to exclude.",
        ),
        field(
            "auth.mount_ssh_socket",
            true,
            vec!["true", "false"],
            json!(false),
            "Mount SSH agent socket.",
        ),
        field(
            "auth.mount_docker_socket",
            true,
            vec!["true", "false"],
            json!(false),
            "Mount Docker socket; high privilege.",
        ),
        field(
            "setup.preset",
            false,
            vec!["none", "builtin", "custom"],
            json!("builtin"),
            "Sandbox setup strategy.",
        ),
        field(
            "setup.required_commands",
            false,
            vec!["command name[]"],
            json!(["claude", "claude-ds"]),
            "Commands that must exist after setup.",
        ),
        field(
            "setup.run_as",
            false,
            vec!["root", "harnesslab", "current"],
            json!("harnesslab"),
            "User used to run the agent command.",
        ),
        field(
            "setup.commands",
            false,
            vec!["shell command[]"],
            json!([]),
            "Advanced custom setup commands.",
        ),
        field(
            "skills.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default skills.",
        ),
        field(
            "skills.allow",
            false,
            vec!["string[]"],
            json!(["skill-a"]),
            "Skill whitelist.",
        ),
        field(
            "skills.deny",
            false,
            vec!["string[]"],
            json!(["skill-b"]),
            "Skill blacklist.",
        ),
        field(
            "skills.include_paths",
            false,
            vec!["path[]"],
            json!(["~/.claude/skills"]),
            "Extra skill paths.",
        ),
        field(
            "tools.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default tools.",
        ),
        field(
            "tools.allow",
            false,
            vec!["string[]"],
            json!(["bash"]),
            "Tool whitelist.",
        ),
        field(
            "tools.deny",
            false,
            vec!["string[]"],
            json!(["web_search"]),
            "Tool blacklist.",
        ),
        field(
            "hooks.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default hooks.",
        ),
        field(
            "hooks.allow",
            false,
            vec!["string[]"],
            json!(["pre_tool_use"]),
            "Hook whitelist.",
        ),
        field(
            "hooks.deny",
            false,
            vec!["string[]"],
            json!(["post_tool_use"]),
            "Hook blacklist.",
        ),
        field(
            "usage.parser",
            true,
            vec!["none", "regex", "json_path"],
            json!("none"),
            "Token/cost usage parser.",
        ),
        field(
            "labels",
            false,
            vec!["key/value"],
            json!({"model":"deepseek"}),
            "Report labels and benchmark adapter hints.",
        ),
    ]
}

fn field(
    path: &'static str,
    required: bool,
    allowed_values: Vec<&'static str>,
    example: serde_json::Value,
    description: &'static str,
) -> AgentProfileFieldReference {
    AgentProfileFieldReference {
        path,
        required,
        allowed_values,
        example,
        description,
    }
}
