use serde::Serialize;
use serde_json::json;

#[derive(Debug, Clone, Serialize)]
pub struct AgentProfileFieldReference {
    pub path: &'static str,
    pub required: bool,
    pub allowed_values: Vec<&'static str>,
    pub example: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_value: Option<serde_json::Value>,
    pub status: &'static str,
    pub description: &'static str,
}

pub fn agent_profile_field_reference() -> Vec<AgentProfileFieldReference> {
    vec![
        field(
            "schema_version",
            true,
            vec!["1"],
            json!(1),
            "Profile schema version.",
        ),
        field(
            "name",
            true,
            vec!["[a-zA-Z0-9][a-zA-Z0-9._-]*"],
            json!("claude-ds"),
            "Profile name used by --agent.",
        ),
        field(
            "kind",
            true,
            vec![
                "codex",
                "claude-code",
                "opencode",
                "pi-coding-agent",
                "custom",
                "fake",
            ],
            json!("claude-code"),
            "CLI harness kind.",
        ),
        field(
            "display_name",
            true,
            vec!["string"],
            json!("Claude DS"),
            "Human-readable report name.",
        ),
        field(
            "command",
            true,
            vec!["shell command"],
            json!("claude-ds -p --bare --output-format text"),
            "Agent command template.",
        ),
        field(
            "input_mode",
            true,
            vec!["argument", "file", "stdin", "tty"],
            json!("stdin"),
            "How the task instruction is passed to the agent.",
        ),
        field(
            "working_dir",
            true,
            vec!["workspace", "run_dir"],
            json!("workspace"),
            "Agent working directory.",
        ),
        field(
            "timeout_sec",
            true,
            vec!["positive integer"],
            json!(300),
            "Default per-task agent timeout.",
        ),
        field(
            "version_command",
            false,
            vec!["shell command"],
            json!("claude --version"),
            "Optional bounded CLI version probe.",
        ),
        field(
            "auth.inherit",
            true,
            vec!["true", "false"],
            json!(true),
            "Enable declared auth env/path inheritance.",
        ),
        field(
            "auth.inherit_env",
            true,
            vec!["string[]"],
            json!(["ANTHROPIC_AUTH_TOKEN"]),
            "Environment variable names to pass through.",
        ),
        field(
            "auth.include_paths",
            true,
            vec!["path[]", "host:container:mode[]"],
            json!([]),
            "Auth/config paths to mount.",
        ),
        field(
            "auth.exclude_paths",
            true,
            vec!["path[]"],
            json!([]),
            "Inherited auth paths to exclude.",
        ),
        field(
            "auth.mount_ssh_socket",
            true,
            vec!["true", "false"],
            json!(false),
            "Mount SSH agent socket.",
        ),
        field(
            "auth.mount_docker_socket",
            true,
            vec!["true", "false"],
            json!(false),
            "Mount Docker socket; high privilege.",
        ),
        field(
            "setup.preset",
            false,
            vec!["none", "builtin", "custom"],
            json!("builtin"),
            "Sandbox setup strategy.",
        ),
        field(
            "setup.required_commands",
            false,
            vec!["command name[]"],
            json!(["claude", "claude-ds"]),
            "Commands that must exist after setup.",
        ),
        field(
            "setup.run_as",
            false,
            vec!["root", "harnesslab", "current"],
            json!("harnesslab"),
            "User used to run the agent command.",
        ),
        field(
            "setup.commands",
            false,
            vec!["shell command[]"],
            json!([]),
            "Advanced custom setup commands.",
        ),
        field(
            "skills.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default skills.",
        ),
        field(
            "skills.allow",
            false,
            vec!["string[]"],
            json!(["skill-a"]),
            "Skill whitelist.",
        ),
        field(
            "skills.deny",
            false,
            vec!["string[]"],
            json!(["skill-b"]),
            "Skill blacklist.",
        ),
        field(
            "skills.include_paths",
            false,
            vec!["path[]"],
            json!(["~/.claude/skills"]),
            "Extra skill paths.",
        ),
        field(
            "tools.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default tools.",
        ),
        field(
            "tools.allow",
            false,
            vec!["string[]"],
            json!(["bash"]),
            "Tool whitelist.",
        ),
        field(
            "tools.deny",
            false,
            vec!["string[]"],
            json!(["web_search"]),
            "Tool blacklist.",
        ),
        field(
            "hooks.inherit",
            false,
            vec!["true", "false"],
            json!(true),
            "Inherit default hooks.",
        ),
        field(
            "hooks.allow",
            false,
            vec!["string[]"],
            json!(["pre_tool_use"]),
            "Hook whitelist.",
        ),
        field(
            "hooks.deny",
            false,
            vec!["string[]"],
            json!(["post_tool_use"]),
            "Hook blacklist.",
        ),
        field(
            "usage.parser",
            true,
            vec!["none", "regex", "json_path"],
            json!("none"),
            "Token/cost usage parser.",
        ),
        field_with_default(
            "usage.source",
            false,
            vec![
                "agent_stdout",
                "agent_stderr",
                "agent_logs",
                "file:<safe-relative-path>",
            ],
            json!("agent_logs"),
            Some(json!("agent_logs")),
            "Input source for usage parsing.",
        ),
        field_with_default(
            "usage.input_tokens_key",
            false,
            vec!["string"],
            json!("input_tokens"),
            Some(json!("input_tokens")),
            "Field/key name for input tokens.",
        ),
        field_with_default(
            "usage.output_tokens_key",
            false,
            vec!["string"],
            json!("output_tokens"),
            Some(json!("output_tokens")),
            "Field/key name for output tokens.",
        ),
        field_with_default(
            "usage.total_tokens_key",
            false,
            vec!["string"],
            json!("total_tokens"),
            Some(json!("total_tokens")),
            "Field/key name for total tokens.",
        ),
        field_with_default(
            "usage.cost_usd_key",
            false,
            vec!["string"],
            json!("cost_usd"),
            Some(json!("cost_usd")),
            "Field/key name for USD cost.",
        ),
        field(
            "labels",
            false,
            vec!["key/value"],
            json!({"model":"deepseek"}),
            "Open report labels and benchmark adapter hints map.",
        ),
        field(
            "labels.model",
            false,
            vec!["string"],
            json!("deepseek"),
            "Common report model/config label.",
        ),
        field(
            "labels.terminal_bench_agent",
            false,
            vec!["terminal-bench agent name"],
            json!("codex"),
            "Terminal-Bench built-in agent name.",
        ),
        field(
            "labels.terminal_bench_agent_import_path",
            false,
            vec!["python import path"],
            json!("harnesslab_tb_agent:HarnessLabCommandAgent"),
            "Terminal-Bench import-path bridge agent.",
        ),
        field(
            "labels.terminal_bench_agent_pythonpath",
            false,
            vec!["absolute path", "python path string"],
            json!("/repo/integrations/terminal_bench"),
            "Python path prepended before loading the Terminal-Bench bridge.",
        ),
        field(
            "labels.terminal_bench_model",
            false,
            vec!["string"],
            json!("deepseek"),
            "Model label consumed by Terminal-Bench built-in agents.",
        ),
        field_with_status(
            "labels.sandbox_setup_command",
            false,
            vec!["shell command"],
            json!("npm install -g @anthropic-ai/claude-code"),
            "legacy",
            "Legacy setup escape hatch; new profiles should use [setup].",
        ),
    ]
}

fn field(
    path: &'static str,
    required: bool,
    allowed_values: Vec<&'static str>,
    example: serde_json::Value,
    description: &'static str,
) -> AgentProfileFieldReference {
    field_with_default_and_status(
        path,
        required,
        allowed_values,
        example,
        None,
        "active",
        description,
    )
}

fn field_with_default(
    path: &'static str,
    required: bool,
    allowed_values: Vec<&'static str>,
    example: serde_json::Value,
    default_value: Option<serde_json::Value>,
    description: &'static str,
) -> AgentProfileFieldReference {
    field_with_default_and_status(
        path,
        required,
        allowed_values,
        example,
        default_value,
        "active",
        description,
    )
}

fn field_with_status(
    path: &'static str,
    required: bool,
    allowed_values: Vec<&'static str>,
    example: serde_json::Value,
    status: &'static str,
    description: &'static str,
) -> AgentProfileFieldReference {
    field_with_default_and_status(
        path,
        required,
        allowed_values,
        example,
        None,
        status,
        description,
    )
}

fn field_with_default_and_status(
    path: &'static str,
    required: bool,
    allowed_values: Vec<&'static str>,
    example: serde_json::Value,
    default_value: Option<serde_json::Value>,
    status: &'static str,
    description: &'static str,
) -> AgentProfileFieldReference {
    AgentProfileFieldReference {
        path,
        required,
        allowed_values,
        example,
        default_value,
        status,
        description,
    }
}
