import { fireEvent, render, screen, within } from '@testing-library/react'
import { beforeEach, describe, expect, it } from 'vitest'
import { App } from './App'

describe('Environment templates', () => {
  beforeEach(() => {
    window.localStorage.clear()
    window.location.hash = ''
  })

  it('manages OrnnLab-local templates over Harbor config fields', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Environment' }))
    expect(screen.getByRole('heading', { name: 'Environment catalog' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'New Environment' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Profile' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Type' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Docker image name / registry URL' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Network mode' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'CPU / memory policy' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Runtime overrides' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Actions' })).toBeInTheDocument()

    const builtinRow = screen.getByText('Docker default').closest('tr')
    const customRow = screen.getByText('Docker GPU').closest('tr')
    expect(builtinRow).not.toBeNull()
    expect(customRow).not.toBeNull()
    expect(within(builtinRow as HTMLElement).getByRole('button', { name: 'Copy' })).toBeInTheDocument()
    expect(within(builtinRow as HTMLElement).queryByRole('button', { name: 'Edit' })).not.toBeInTheDocument()
    expect(within(customRow as HTMLElement).queryByRole('button', { name: 'Edit' })).not.toBeInTheDocument()
    expect(within(customRow as HTMLElement).getByRole('button', { name: 'Delete' })).toBeInTheDocument()

    fireEvent.click(within(builtinRow as HTMLElement).getByRole('button', { name: 'Copy' }))
    expect(screen.getByRole('heading', { name: 'Copy Environment' })).toBeInTheDocument()
    expect(window.location.hash).toBe('#environments/docker-default/copy')
    fireEvent.click(screen.getByRole('button', { name: 'Save' }))
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    expect(screen.getByText('Docker default copy')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'New Environment' }))
    expect(screen.getByRole('heading', { name: 'New Environment' })).toBeInTheDocument()
    expect(window.location.hash).toBe('#environments/new')
    fireEvent.change(screen.getByLabelText('Environment Name'), { target: { value: 'Docker local tmp' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save' }))
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    expect(screen.getByText('Docker local tmp')).toBeInTheDocument()

    const customRowForEdit = screen.getByText('Docker GPU').closest('tr')
    expect(customRowForEdit).not.toBeNull()
    fireEvent.click(customRowForEdit as HTMLElement)
    const editableEnvironmentDialog = screen.getByRole('dialog', { name: 'Selected environment' })
    expect(within(editableEnvironmentDialog).getByRole('tab', { name: 'Basic' })).toHaveAttribute('aria-selected', 'true')
    expect(within(editableEnvironmentDialog).queryByRole('tab', { name: 'Environment' })).not.toBeInTheDocument()
    expect(within(editableEnvironmentDialog).getByRole('tab', { name: 'Network' })).toBeInTheDocument()
    expect(within(editableEnvironmentDialog).getByRole('tab', { name: 'Advanced' })).toBeInTheDocument()
    expect(within(editableEnvironmentDialog).getByLabelText('Environment Name')).toBeInTheDocument()
    const environmentTypeSelect = within(editableEnvironmentDialog).getByLabelText('Type')
    expect(environmentTypeSelect).toHaveAttribute('aria-haspopup', 'listbox')
    fireEvent.click(environmentTypeSelect)
    expect(within(editableEnvironmentDialog).queryByRole('option', { name: 'custom' })).not.toBeInTheDocument()
    expect(within(editableEnvironmentDialog).getByLabelText('Import path')).toHaveValue('')
    expect(within(editableEnvironmentDialog).getByLabelText('OS')).toHaveAttribute('aria-haspopup', 'listbox')
    expect(within(editableEnvironmentDialog).getAllByLabelText('TPU type')[0]).toHaveAttribute('aria-haspopup', 'listbox')
    expect(within(editableEnvironmentDialog).getAllByLabelText('Topology X')[0]).toHaveAttribute('type', 'number')
    expect(within(editableEnvironmentDialog).getAllByLabelText('Topology Y')[0]).toHaveAttribute('type', 'number')
    expect(within(editableEnvironmentDialog).getAllByLabelText('Topology Z')[0]).toHaveAttribute('type', 'number')
    expect(within(editableEnvironmentDialog).getByText('Environment variables')).toBeInTheDocument()
    expect(within(editableEnvironmentDialog).queryByLabelText('network_mode')).not.toBeInTheDocument()
    fireEvent.click(within(editableEnvironmentDialog).getByRole('tab', { name: 'Network' }))
    expect(within(editableEnvironmentDialog).getByRole('checkbox', { name: 'Network access' })).toBeChecked()
    expect(within(editableEnvironmentDialog).getByLabelText('Allowed hosts 1')).toHaveValue('pypi.org')
    expect(within(editableEnvironmentDialog).getByLabelText('Allowed hosts 2')).toHaveValue('github.com')
    expect(within(editableEnvironmentDialog).getByLabelText('Allowed hosts 3')).toHaveValue('huggingface.co')
    fireEvent.click(within(editableEnvironmentDialog).getByRole('checkbox', { name: 'Network access' }))
    expect(within(editableEnvironmentDialog).queryByLabelText('Allowed hosts 1')).not.toBeInTheDocument()
    fireEvent.click(within(editableEnvironmentDialog).getByRole('checkbox', { name: 'Network access' }))
    expect(within(editableEnvironmentDialog).getByLabelText('Allowed hosts 1')).toHaveValue('*')
    fireEvent.click(within(editableEnvironmentDialog).getByRole('tab', { name: 'Advanced' }))
    expect(within(editableEnvironmentDialog).getByLabelText('Force rebuild')).toHaveAttribute('type', 'checkbox')
    expect(within(editableEnvironmentDialog).getByLabelText('CPU policy')).toHaveAttribute('aria-haspopup', 'listbox')
    expect(within(editableEnvironmentDialog).getByLabelText('Extra Docker Compose 1')).toHaveValue('compose.gpu.yml')
    expect(within(editableEnvironmentDialog).getByLabelText('Extra allowed hosts')).toBeInTheDocument()
    expect(within(editableEnvironmentDialog).getAllByRole('button', { name: 'Add' }).length).toBeGreaterThan(0)
    expect(within(editableEnvironmentDialog).getAllByRole('button', { name: 'Delete' }).length).toBeGreaterThan(0)
    fireEvent.click(within(editableEnvironmentDialog).getByRole('tab', { name: 'Basic' }))
    fireEvent.change(screen.getByLabelText('Environment Name'), { target: { value: 'Docker GPU tuned' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save' }))
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    expect(screen.getByText('Docker GPU tuned')).toBeInTheDocument()

    fireEvent.click(screen.getByText('Docker GPU tuned'))
    const environmentDialog = screen.getByRole('dialog', { name: 'Selected environment' })
    expect(within(environmentDialog).getByDisplayValue('nvidia/cuda:12.4-runtime')).toBeInTheDocument()
    fireEvent.click(within(environmentDialog).getByRole('tab', { name: 'Advanced' }))
    expect(within(environmentDialog).getByLabelText('CPU policy')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))

    const copiedRow = screen.getByText('Docker default copy').closest('tr')
    expect(copiedRow).not.toBeNull()
    fireEvent.click(within(copiedRow as HTMLElement).getByRole('button', { name: 'Delete' }))
    expect(screen.getByRole('dialog', { name: 'Delete custom environment' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Confirm delete' }))
    expect(screen.queryByText('Docker default copy')).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('link', { name: 'Jobs' }))
    fireEvent.click(screen.getByRole('button', { name: 'New Job' }))
    fireEvent.click(screen.getByRole('button', { name: 'Environment' }))
    expect(screen.getByRole('option', { name: 'Docker local tmp' })).toBeInTheDocument()

    fireEvent.click(screen.getByRole('link', { name: 'Environment' }))
    fireEvent.change(screen.getByLabelText('Search environments'), { target: { value: 'e2b' } })
    expect(screen.getByText('E2B sandbox')).toBeInTheDocument()
    expect(screen.queryByText('Docker default')).not.toBeInTheDocument()
  })
})
