import { act, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { App } from './App'

describe('App', () => {
  beforeEach(() => {
    window.localStorage.clear()
    window.location.hash = ''
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('renders jobs as the default Harbor operating surface', () => {
    render(<App />)

    expect(screen.getByRole('heading', { name: 'Job registry' })).toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'Jobs' })).toHaveClass('active')
    expect(within(screen.getByRole('banner')).queryByRole('button', { name: 'Run job' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'New Job' })).toBeInTheDocument()
    const jobsTable = screen.getByRole('table')
    expect(within(jobsTable).queryByRole('columnheader', { name: 'Updated' })).not.toBeInTheDocument()
    expect(within(jobsTable).getByRole('columnheader', { name: 'Token usage (M)' })).toBeInTheDocument()
    expect(within(jobsTable).getByRole('columnheader', { name: 'Runtime duration' })).toBeInTheDocument()
    expect(within(jobsTable).getByRole('columnheader', { name: 'Created time' })).toBeInTheDocument()
    expect(within(jobsTable).getByText('72.5%')).toBeInTheDocument()
    expect(within(jobsTable).getByText('87/100')).toBeInTheDocument()
    expect(within(jobsTable).queryByText('0.72')).not.toBeInTheDocument()
    expect(within(jobsTable).getByText('0.0184M')).toBeInTheDocument()
    expect(within(jobsTable).getByText('00:42:18')).toBeInTheDocument()
    expect(within(jobsTable).getByText('2026-06-29 03:46:12')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'terminal-bench-smoke' }).closest('.job-identity')).not.toBeNull()
    expect(screen.queryByRole('dialog', { name: 'Selected job' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'terminal-bench-smoke' }))
    const jobDialog = screen.getByRole('dialog', { name: 'Selected job' })
    expect(jobDialog).toBeInTheDocument()
    expect(jobDialog).toHaveStyle({ width: '560px' })
    const resizeHandle = screen.getByRole('separator', { name: 'Resize detail drawer' })
    fireEvent.pointerDown(resizeHandle, { buttons: 1, clientX: 360, pointerId: 1 })
    fireEvent.pointerMove(resizeHandle, { buttons: 1, clientX: 320, pointerId: 1 })
    expect(jobDialog).toHaveStyle({ width: '704px' })
    expect(within(jobDialog).queryByText('Selected job')).not.toBeInTheDocument()
    expect(screen.getByText('Job trials')).toBeInTheDocument()
    expect(screen.queryByText('Hub actions')).not.toBeInTheDocument()
    expect(within(jobDialog).getByRole('button', { name: 'Pause' })).toBeInTheDocument()
    expect(within(jobDialog).queryByRole('button', { name: 'Resume' })).not.toBeInTheDocument()
    expect(within(jobDialog).getByRole('checkbox', { name: 'Include in leaderboard' })).toBeChecked()
    expect(screen.queryByRole('button', { name: 'Summarize' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Open viewer' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Analyze' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Upload' })).toBeInTheDocument()
    expect(within(jobDialog).queryByRole('button', { name: 'Download' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Share' })).not.toBeInTheDocument()
    expect(screen.getByText('/Users/xuzhang/.ornnlab/HarnessLab/jobs/terminal-bench-smoke/harbor.capability.json')).toBeInTheDocument()
    expect(screen.getByText('/Users/xuzhang/.ornnlab/HarnessLab/trials/job_91a7')).toBeInTheDocument()
    expect(screen.queryByText('harbor.config.json', { exact: true })).not.toBeInTheDocument()
    expect(screen.queryByText('job.log', { exact: true })).not.toBeInTheDocument()
    expect(screen.getByText('Log file')).toBeInTheDocument()
    expect(screen.getAllByText('/Users/xuzhang/.ornnlab/HarnessLab/jobs/terminal-bench-smoke/job.log')).toHaveLength(2)
    expect(screen.queryByText('Trial diagnostics')).not.toBeInTheDocument()
    expect(screen.queryByText('analysis: trials/job_91a7/apt-setup.analysis.json')).not.toBeInTheDocument()
    expect(screen.queryByText('log path: trials/job_91a7/apt-setup.log')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /apt-setup/i }))
    expect(screen.getByText('retries: 0')).toBeInTheDocument()
    expect(screen.getByText('log path: trials/job_91a7/apt-setup.log')).toBeInTheDocument()
  })

  it('renders datasets as the Harbor catalog surface', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Datasets' }))
    expect(screen.getByRole('heading', { name: 'Dataset catalog' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Import local Dataset' }))
    expect(screen.getByRole('dialog', { name: 'Import local Dataset' })).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Dataset name'), { target: { value: 'local/math-eval' } })
    fireEvent.change(screen.getByLabelText('Local path'), { target: { value: './datasets/math-eval' } })
    fireEvent.change(screen.getByLabelText('Tasks'), { target: { value: '24' } })
    fireEvent.click(screen.getByRole('button', { name: 'Confirm import' }))
    expect(screen.queryByRole('dialog', { name: 'Import local Dataset' })).not.toBeInTheDocument()
    expect(screen.getAllByText('local/math-eval').length).toBeGreaterThan(0)
    expect(screen.getAllByText('./datasets/math-eval').length).toBeGreaterThan(0)
    expect(screen.getAllByText('local import').length).toBeGreaterThan(0)
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    const datasetsTable = screen.getByRole('table')
    expect(within(datasetsTable).queryByRole('columnheader', { name: 'Digest' })).not.toBeInTheDocument()
    expect(within(datasetsTable).queryByRole('columnheader', { name: 'Updated' })).not.toBeInTheDocument()
    expect(within(datasetsTable).getByRole('columnheader', { name: 'Path' })).toBeInTheDocument()
    expect(within(datasetsTable).getByRole('columnheader', { name: 'Size' })).toBeInTheDocument()
    expect(within(datasetsTable).getByRole('columnheader', { name: 'Actions' })).toBeInTheDocument()
    expect(within(datasetsTable).getByText('~/.cache/harbor/datasets/terminal-bench')).toBeInTheDocument()
    expect(within(datasetsTable).getByText('1.2 GB')).toBeInTheDocument()
    expect(within(datasetsTable).getAllByText('Not downloaded').length).toBeGreaterThan(0)
    const sweRow = screen.getByText('swe-bench-lite').closest('tr')
    expect(sweRow).not.toBeNull()
    vi.useFakeTimers()
    fireEvent.click(within(sweRow as HTMLElement).getByRole('button', { name: 'Download' }))
    expect(screen.queryByRole('dialog', { name: 'Selected dataset' })).not.toBeInTheDocument()
    expect(within(sweRow as HTMLElement).getByText('0%')).toBeInTheDocument()
    act(() => vi.advanceTimersByTime(800))
    expect(within(sweRow as HTMLElement).getByText('20%')).toBeInTheDocument()
    fireEvent.click(within(sweRow as HTMLElement).getByRole('button', { name: 'Cancel download' }))
    expect(within(sweRow as HTMLElement).getAllByText('Not downloaded').length).toBeGreaterThan(0)
    const terminalRow = screen.getByText('terminal-bench').closest('tr')
    expect(terminalRow).not.toBeNull()
    fireEvent.click(within(terminalRow as HTMLElement).getByRole('button', { name: 'Delete' }))
    expect(screen.getByRole('dialog', { name: 'Delete local dataset' })).toBeInTheDocument()
    expect(screen.getByText('This removes the downloaded dataset files from local storage.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Confirm delete' }))
    expect(within(terminalRow as HTMLElement).getAllByText('Not downloaded').length).toBeGreaterThan(0)
    expect(screen.getAllByText('terminal-bench').length).toBeGreaterThan(0)
    expect(screen.queryByRole('dialog', { name: 'Selected dataset' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByText('terminal-bench'))
    const datasetDialog = screen.getByRole('dialog', { name: 'Selected dataset' })
    expect(datasetDialog).toBeInTheDocument()
    expect(within(datasetDialog).queryByText('Selected dataset')).not.toBeInTheDocument()
    expect(screen.getByText('Dataset tasks')).toBeInTheDocument()
    expect(within(datasetDialog).getByText('Task')).toBeInTheDocument()
    expect(within(datasetDialog).queryByText('OS')).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByText('Description')).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByText('Verifier')).not.toBeInTheDocument()
    expect(within(datasetDialog).getByText('Actions')).toBeInTheDocument()
    expect(within(datasetDialog).queryByText('Install packages and verify shell setup.')).not.toBeInTheDocument()
    fireEvent.click(within(datasetDialog).getByText('apt-setup'))
    expect(within(datasetDialog).getByText('Description')).toBeInTheDocument()
    expect(within(datasetDialog).getByText('Install packages and verify shell setup.')).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: 'Run single task' }).length).toBeGreaterThan(0)
    expect(within(datasetDialog).getByText('Splits')).toBeInTheDocument()
    expect(within(datasetDialog).getByText('test', { exact: true })).toBeInTheDocument()
    expect(screen.getByText('registry_url')).toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Init' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Add' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Remove' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'New Job' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('checkbox', { name: 'Include in leaderboard' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Start environment' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Check' })).not.toBeInTheDocument()
    expect(within(datasetDialog).queryByRole('button', { name: 'Debug' })).not.toBeInTheDocument()
    expect(screen.getByText('Manifest tools')).toBeInTheDocument()
    expect(screen.queryByText('Task config')).not.toBeInTheDocument()
    expect(screen.queryByText('schema_version: 1.0')).not.toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'Datasets' })).toHaveClass('active')
  })

  it('renders the jobs hierarchy without flattening the run builder into it', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Jobs' }))
    expect(screen.getByRole('heading', { name: 'Job registry' })).toBeInTheDocument()
    expect(screen.getAllByText('terminal-bench-smoke').length).toBeGreaterThan(0)
    fireEvent.click(screen.getByRole('button', { name: 'terminal-bench-smoke' }))
    expect(screen.getByRole('dialog', { name: 'Selected job' })).toBeInTheDocument()
    expect(screen.getByText('Job trials')).toBeInTheDocument()
    expect(screen.getByText('apt-setup')).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'System doctor' })).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'New Run' })).not.toBeInTheDocument()
    expect(screen.queryByRole('link', { name: 'New Run' })).not.toBeInTheDocument()
    expect(screen.queryByLabelText('Job creation path')).not.toBeInTheDocument()
  })

  it('filters jobs and keeps the table as the primary surface', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Jobs' }))
    fireEvent.change(screen.getByLabelText('Search jobs'), { target: { value: 'swe' } })

    const jobsTable = screen.getByRole('table')
    expect(screen.getByText('swe-bench-lite-regression')).toBeInTheDocument()
    expect(within(jobsTable).queryByText('terminal-bench-smoke')).not.toBeInTheDocument()
  })

  it('keeps task and trial concepts nested under datasets and jobs', () => {
    render(<App />)

    expect(screen.queryByRole('link', { name: 'Tasks' })).not.toBeInTheDocument()
    expect(screen.queryByRole('link', { name: 'Trials' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('link', { name: 'Datasets' }))
    fireEvent.click(screen.getByText('terminal-bench'))
    expect(screen.getByText('Dataset tasks')).toBeInTheDocument()

    fireEvent.click(screen.getByRole('link', { name: 'Jobs' }))
    fireEvent.click(screen.getByRole('button', { name: 'terminal-bench-smoke' }))
    expect(screen.getByText('Job trials')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('link', { name: 'System' }))
    expect(screen.getByRole('heading', { name: 'System health' })).toBeInTheDocument()
  })

  it('renders agents and dataset-scoped leaderboard pages', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Agents' }))
    expect(screen.getByRole('heading', { name: 'Agent catalog' })).toBeInTheDocument()
    expect(screen.getByLabelText('Search agents')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'New Agent' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Agent Name' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Harness' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Actions' })).toBeInTheDocument()
    expect(screen.queryByRole('columnheader', { name: 'Adapter' })).not.toBeInTheDocument()
    expect(screen.queryByRole('columnheader', { name: 'Source' })).not.toBeInTheDocument()
    expect(screen.queryByRole('columnheader', { name: 'Updated' })).not.toBeInTheDocument()
    expect(screen.getByText('Claude Code default')).toBeInTheDocument()
    expect(screen.getByText('claude-code')).toBeInTheDocument()
    expect(screen.getByText('Local repair agent')).toBeInTheDocument()
    expect(screen.getByText('custom-harness')).toBeInTheDocument()
    const builtinRow = screen.getByText('Claude Code default').closest('tr')
    expect(builtinRow).not.toBeNull()
    expect(within(builtinRow as HTMLElement).queryByRole('button', { name: 'Delete' })).not.toBeInTheDocument()
    const customRow = screen.getByText('Local repair agent').closest('tr')
    expect(customRow).not.toBeNull()
    fireEvent.click(within(customRow as HTMLElement).getByRole('button', { name: 'Delete' }))
    expect(screen.getByRole('dialog', { name: 'Delete custom agent' })).toBeInTheDocument()
    expect(screen.getByText('This removes the custom agent configuration from the local WebUI list.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    fireEvent.change(screen.getByLabelText('Search agents'), { target: { value: 'local' } })
    expect(screen.getByText('Local repair agent')).toBeInTheDocument()
    expect(screen.queryByText('claude-code')).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Search agents'), { target: { value: '' } })
    expect(screen.queryByRole('dialog', { name: 'Selected agent' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByText('Local repair agent'))
    const agentDialog = screen.getByRole('dialog', { name: 'Selected agent' })
    expect(agentDialog).toBeInTheDocument()
    expect(within(agentDialog).queryByText('Selected agent')).not.toBeInTheDocument()
    expect(screen.getAllByText('custom-harness').length).toBeGreaterThan(0)
    expect(screen.getByText('env readiness')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Adapter init' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Adapter review' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Validate' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Compile' })).not.toBeInTheDocument()
    expect(screen.getByText('extra_allowed_hosts: localhost, model.internal')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    fireEvent.click(within(customRow as HTMLElement).getByRole('button', { name: 'Delete' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm delete' }))
    expect(screen.queryByText('Local repair agent')).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('link', { name: 'Leaderboard' }))
    expect(screen.getByRole('heading', { name: 'Leaderboard' })).toBeInTheDocument()
    expect(screen.getByText('Metric')).toBeInTheDocument()
    expect(screen.queryByText('Submission')).not.toBeInTheDocument()
    expect(screen.queryByText('Uploaded URL')).not.toBeInTheDocument()
    expect(screen.getByLabelText('Agent filter')).toBeInTheDocument()
    expect(screen.queryByText('Reproducibility')).not.toBeInTheDocument()
    expect(screen.getByLabelText('Select dataset')).toHaveTextContent('terminal-bench@2.0')
    expect(screen.getByRole('columnheader', { name: 'Agent Name' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Harness' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Tokens (M)' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Actions' })).toBeInTheDocument()
    expect(screen.getByText('Claude Code default')).toBeInTheDocument()
    expect(screen.getByText('claude-code')).toBeInTheDocument()
    expect(screen.getByText('0.0184M')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Submit' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Open report' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'job_91a7' }))
    expect(screen.getByRole('dialog', { name: 'Selected job' })).toBeInTheDocument()
    expect(screen.getByText('Job trials')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Close detail drawer' }))
    const firstRankRow = screen.getByText('job_91a7').closest('tr')
    expect(firstRankRow).not.toBeNull()
    fireEvent.click(within(firstRankRow as HTMLElement).getByRole('button', { name: 'Remove' }))
    expect(screen.queryByText('job_91a7')).not.toBeInTheDocument()
    const nextRankRow = screen.getByText('job_64f2').closest('tr')
    expect(nextRankRow).not.toBeNull()
    expect(within(nextRankRow as HTMLElement).getByText('#1')).toBeInTheDocument()

    fireEvent.change(screen.getByLabelText('Search datasets'), { target: { value: 'swe' } })
    fireEvent.click(screen.getByLabelText('Select dataset'))
    fireEvent.click(screen.getByRole('option', { name: 'swe-bench-lite@2026.06' }))
    expect(screen.getByText('job_74c1')).toBeInTheDocument()
    expect(screen.getByText('claude-sonnet-4-5')).toBeInTheDocument()
    expect(screen.getByText('gpt-5.1')).toBeInTheDocument()
    expect(screen.queryByLabelText('Search leaderboard')).not.toBeInTheDocument()
  })

  it('switches language and theme from the header', () => {
    render(<App />)

    expect(screen.getByRole('button', { name: 'Hub connected' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Login' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Logout' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Language'))
    fireEvent.click(screen.getByRole('option', { name: '中' }))
    expect(screen.getByRole('heading', { name: 'Job 管理' })).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: '深色' }))
    expect(document.documentElement.dataset.theme).toBe('dark')
  })

  it('adds a queued job from the dedicated new run flow', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'Jobs' }))
    expect(within(screen.getByRole('banner')).queryByRole('button', { name: 'Run job' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'New Job' }))
    expect(window.location.hash).toBe('#jobs/new')
    expect(screen.getByRole('link', { name: 'Jobs' })).toHaveClass('active')
    expect(screen.getByRole('navigation', { name: 'Job creation path' })).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Job creation path' })).getByRole('button', { name: 'Jobs' }))
    expect(screen.getByRole('heading', { name: 'Job registry' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'New Job' }))
    let runBuilder = screen.getByRole('heading', { name: 'New Job' }).closest('section')
    expect(runBuilder).not.toBeNull()
    expect(within(runBuilder as HTMLElement).getByRole('button', { name: 'Cancel' })).toBeInTheDocument()
    expect(within(runBuilder as HTMLElement).getByRole('button', { name: 'Reset' })).toBeInTheDocument()
    expect(within(runBuilder as HTMLElement).getByRole('button', { name: 'JobConfig' })).toBeInTheDocument()
    fireEvent.click(within(runBuilder as HTMLElement).getByRole('button', { name: 'Cancel' }))
    expect(screen.getByRole('heading', { name: 'Job registry' })).toBeInTheDocument()
    expect(window.location.hash).toBe('#jobs')
    fireEvent.click(screen.getByRole('button', { name: 'New Job' }))
    runBuilder = screen.getByRole('heading', { name: 'New Job' }).closest('section')
    expect(runBuilder).not.toBeNull()
    expect(within(runBuilder as HTMLElement).getByRole('tab', { name: 'Basic' })).toHaveAttribute('aria-selected', 'true')
    expect(within(runBuilder as HTMLElement).getByRole('tab', { name: 'Tasks' })).toBeInTheDocument()
    expect(within(runBuilder as HTMLElement).queryByRole('tab', { name: 'Environment' })).not.toBeInTheDocument()
    expect(within(runBuilder as HTMLElement).queryByRole('tab', { name: 'Agent' })).not.toBeInTheDocument()
    expect(screen.getByLabelText('job_name')).toHaveValue('terminal-bench-smoke')
    expect(screen.getByLabelText('Environment')).toHaveTextContent('Docker default')
    expect(screen.queryByLabelText('Model')).not.toBeInTheDocument()
    expect(screen.getByLabelText('debug模式')).toHaveTextContent('disabled')
    expect(screen.queryByLabelText('yes')).not.toBeInTheDocument()
    expect(screen.queryByLabelText('env_file')).not.toBeInTheDocument()
    expect(screen.getByLabelText('Include in leaderboard')).toHaveTextContent('enabled')
    expect(screen.getByLabelText('Notes')).toHaveValue('')
    fireEvent.change(screen.getByLabelText('Notes'), { target: { value: 'nightly smoke run' } })
    expect(screen.getByLabelText('Notes')).toHaveValue('nightly smoke run')
    expect(screen.queryByLabelText('Split')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('tab', { name: 'Tasks' }))
    expect(screen.getByLabelText('Split')).toHaveTextContent('test')
    expect(screen.getByLabelText('extra_instruction_paths')).toHaveValue('instructions/hardening.md')
    expect(screen.getByRole('region', { name: 'Task whitelist' })).toHaveTextContent('Selected tasks: 4 / 4')
    expect(screen.getByLabelText(/apt-setup/)).toBeChecked()
    fireEvent.change(screen.getByLabelText('Search tasks'), { target: { value: 'sqlite' } })
    expect(screen.getByText('sqlite-log-repair')).toBeInTheDocument()
    expect(screen.queryByText('apt-setup')).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Search tasks'), { target: { value: '' } })
    fireEvent.click(screen.getByLabelText(/apt-setup/))
    expect(screen.getByRole('region', { name: 'Task whitelist' })).toHaveTextContent('Selected tasks: 3 / 4')
    fireEvent.click(screen.getByRole('button', { name: 'Disable all' }))
    expect(screen.getByRole('region', { name: 'Task whitelist' })).toHaveTextContent('Selected tasks: 0 / 4')
    fireEvent.click(screen.getByRole('button', { name: 'Enable all' }))
    fireEvent.change(screen.getByLabelText('Search tasks'), { target: { value: 'sqlite' } })
    fireEvent.click(screen.getByRole('button', { name: 'Disable all' }))
    expect(screen.getByRole('region', { name: 'Task whitelist' })).toHaveTextContent('Selected tasks: 3 / 4')
    expect(screen.getByLabelText(/sqlite-log-repair/)).not.toBeChecked()
    fireEvent.click(screen.getByRole('button', { name: 'Enable all' }))
    expect(screen.getByRole('region', { name: 'Task whitelist' })).toHaveTextContent('Selected tasks: 4 / 4')
    expect(screen.queryByLabelText('agent env')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('tab', { name: 'Verifier' }))
    expect(screen.getByLabelText('Verifier mode')).toHaveTextContent('Use Dataset default verifier')
    expect(screen.queryByLabelText('verifier env')).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Verifier mode'))
    fireEvent.click(screen.getByRole('option', { name: 'Custom verifier' }))
    expect(screen.getByLabelText('verifier import_path')).toHaveValue('')
    expect(screen.getByText('verifier env')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('tab', { name: 'Runtime' }))
    expect(screen.getByLabelText('Timeout policy')).toHaveTextContent('Standard (1x)')
    expect(screen.getByLabelText('Failure retries')).toHaveValue(1)
    expect(screen.getByLabelText('Retry interval')).toHaveTextContent('Standard (starts at 2s, max 30s)')
    expect(screen.getByLabelText('Timeout')).toBeChecked()
    expect(screen.queryByLabelText('quiet')).not.toBeInTheDocument()
    expect(screen.queryByLabelText('retry wait multiplier')).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Timeout policy'))
    fireEvent.click(screen.getByRole('option', { name: 'Custom multiplier' }))
    expect(screen.getByLabelText('Timeout policy')).toHaveTextContent('Custom multiplier')
    expect(screen.getByLabelText('Overall timeout multiplier')).toHaveValue(1)
    fireEvent.click(screen.getByLabelText('Retry interval'))
    fireEvent.click(screen.getByRole('option', { name: 'Custom interval' }))
    expect(screen.getByLabelText('Retry interval')).toHaveTextContent('Custom interval')
    expect(screen.getByLabelText('Wait growth multiplier')).toHaveValue(1.5)
    fireEvent.click(screen.getByRole('tab', { name: 'Output' }))
    expect(screen.getByRole('heading', { name: 'Job plugins' })).toBeInTheDocument()
    expect(screen.getByText('No installed harbor.plugins entry point plugins detected.')).toBeInTheDocument()
    expect(screen.getByLabelText('plugin import_path')).toHaveValue('harbor.plugins.cost:CostPlugin')
    expect(screen.getByLabelText('upload to Hub')).toHaveTextContent('disabled')
    expect(screen.queryByText(/harbor run/)).not.toBeInTheDocument()
    expect(screen.queryByText(/--include-task-name apt-\*/)).not.toBeInTheDocument()
    expect(screen.queryByText(/--env-file \.env\.harbor/)).not.toBeInTheDocument()
    const runButton = within(runBuilder as HTMLElement).getByRole('button', { name: 'Run job' })
    fireEvent.click(runButton)

    expect(screen.getAllByText('terminal-bench-draft').length).toBeGreaterThan(0)
    expect(screen.getByRole('heading', { name: 'Job registry' })).toBeInTheDocument()
  })

  it('shows Harbor maintenance operations in system', () => {
    render(<App />)

    fireEvent.click(screen.getByRole('link', { name: 'System' }))
    expect(screen.getByRole('heading', { name: 'System health' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'System checks' })).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'System actions' })).not.toBeInTheDocument()
    expect(screen.queryByText('Interrupted runs reconciled')).not.toBeInTheDocument()
    expect(screen.queryByText('Harbor cache command available')).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Cache' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Hub connected' })).toBeInTheDocument()
    expect(screen.queryByText('Authentication')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Status' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Login' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Logout' })).not.toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Actions' })).toBeInTheDocument()
    expect(screen.getByRole('columnheader', { name: 'Path' })).toBeInTheDocument()
    expect(screen.queryByRole('columnheader', { name: 'Evidence' })).not.toBeInTheDocument()
    expect(screen.getByText('OrnnLab Service')).toBeInTheDocument()
    expect(screen.getByText('0.1.3 latest')).toBeInTheDocument()
    expect(screen.getByText('http://127.0.0.1:5173')).toBeInTheDocument()
    expect(screen.getByText('CPU Usage')).toBeInTheDocument()
    expect(screen.getByText('12%')).toBeInTheDocument()
    expect(screen.getByText('system monitor: cpu')).toBeInTheDocument()
    expect(screen.getByText('GPU Usage')).toBeInTheDocument()
    expect(screen.getByText('0%')).toBeInTheDocument()
    expect(screen.getByText('system monitor: gpu')).toBeInTheDocument()
    expect(screen.getByText('Available Storage')).toBeInTheDocument()
    expect(screen.getByText('48Gi available')).toBeInTheDocument()
    expect(screen.getByText('/Volumes/XU-1TB-NPM')).toBeInTheDocument()
    const systemRows = screen.getAllByRole('row').slice(1)
    expect(systemRows.at(-3)).toHaveTextContent('CPU Usage')
    expect(systemRows.at(-2)).toHaveTextContent('GPU Usage')
    expect(systemRows.at(-1)).toHaveTextContent('Available Storage')
    expect(screen.queryByText('Local cache')).not.toBeInTheDocument()
    expect(screen.getByText('0.01 MB cache')).toBeInTheDocument()
    expect(screen.getByText('~/.cache/harbor')).toBeInTheDocument()
    expect(screen.getByText('docker context: colima')).toBeInTheDocument()
    const serviceRow = screen.getByText('OrnnLab Service').closest('tr')
    expect(serviceRow).not.toBeNull()
    vi.useFakeTimers()
    fireEvent.click(within(serviceRow as HTMLElement).getByRole('button', { name: 'Check update' }))
    expect(screen.getByRole('status')).toHaveTextContent('OrnnLab is already on the latest npm version.')
    expect(screen.getByRole('status')).toHaveTextContent('3s')
    expect(screen.getByRole('button', { name: 'Dismiss' })).toHaveClass('toast-close')
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.getByRole('status')).toHaveTextContent('2s')
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.getByRole('status')).toHaveTextContent('1s')
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
    fireEvent.click(within(serviceRow as HTMLElement).getByRole('button', { name: 'Restart' }))
    expect(screen.getByRole('dialog', { name: 'Restart OrnnLab service' })).toBeInTheDocument()
    expect(screen.queryByText('This forces the OrnnLab frontend and backend services to restart.')).not.toBeInTheDocument()
    expect(screen.getByText('The WebUI may disconnect briefly and reload after the frontend service comes back.')).toBeInTheDocument()
    expect(screen.getByText('Active Harbor orchestration requests may be interrupted while the backend restarts.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(screen.queryByRole('dialog', { name: 'Restart OrnnLab service' })).not.toBeInTheDocument()
    const cpuRow = screen.getByText('CPU Usage').closest('tr')
    expect(cpuRow).not.toBeNull()
    expect(within(cpuRow as HTMLElement).queryByRole('button')).not.toBeInTheDocument()
    const gpuRow = screen.getByText('GPU Usage').closest('tr')
    expect(gpuRow).not.toBeNull()
    expect(within(gpuRow as HTMLElement).queryByRole('button')).not.toBeInTheDocument()
    const availableStorageRow = screen.getByText('Available Storage').closest('tr')
    expect(availableStorageRow).not.toBeNull()
    expect(within(availableStorageRow as HTMLElement).queryByRole('button')).not.toBeInTheDocument()
    const dockerRow = screen.getByText('Docker').closest('tr')
    expect(dockerRow).not.toBeNull()
    fireEvent.click(within(dockerRow as HTMLElement).getByRole('button', { name: 'Clean cache' }))
    expect(screen.getByRole('dialog', { name: 'Clean Docker cache' })).toBeInTheDocument()
    expect(screen.queryByText('This removes Harbor-matched Docker images only.')).not.toBeInTheDocument()
    expect(screen.getByText('Future jobs may need to rebuild or pull images again, increasing startup time.')).toBeInTheDocument()
    expect(screen.queryByText(/harbor cache clean/)).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(screen.queryByRole('dialog', { name: 'Clean Docker cache' })).not.toBeInTheDocument()
    const storageRow = screen.getByText('Storage').closest('tr')
    expect(storageRow).not.toBeNull()
    fireEvent.click(within(storageRow as HTMLElement).getByRole('button', { name: 'Clean cache' }))
    expect(screen.getByRole('dialog', { name: 'Clean local cache' })).toBeInTheDocument()
    expect(screen.queryByText('This removes Harbor local cache data only.')).not.toBeInTheDocument()
    expect(screen.getByText('Deletes the local Harbor cache directory at ~/.cache/harbor.')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Plugins' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Sync' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Upload' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Submit' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Share' })).not.toBeInTheDocument()
    expect(screen.queryByText(/harbor auth/)).not.toBeInTheDocument()
  })
})
