import { expect, test } from '@playwright/test'

test('renders primary Harbor WebUI demo surfaces', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('link', { name: /OrnnLab/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Jobs' })).toHaveClass(/active/)
  await expect(page.getByRole('dialog', { name: 'Selected job' })).toHaveCount(0)
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  await expect(page.getByText('Job trials')).toBeVisible()
  await expect(page.getByText('Hub actions')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open viewer' })).toBeVisible()
  await expect(page.getByText('harbor.capability.json')).toBeVisible()
  await expect(page.getByText('Trial diagnostics')).toBeVisible()
  await expect(page.getByText('analysis: trials/job_91a7/apt-setup.analysis.json')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'Datasets' }).click()
  await expect(page.getByRole('heading', { name: 'Dataset catalog' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Datasets' })).toHaveClass(/active/)
  await expect(page.getByRole('cell', { name: 'terminal-bench', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Selected dataset' })).toHaveCount(0)
  await page.getByRole('cell', { name: 'terminal-bench', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Selected dataset' })).toBeVisible()
  await expect(page.getByText('Dataset tasks')).toBeVisible()
  await expect(page.getByText('registry_url')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start environment' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Debug' }).first()).toBeVisible()
  await expect(page.getByText('Manifest tools')).toBeVisible()
  await expect(page.getByText('Task config')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByLabel('Search datasets').fill('swe')
  await expect(page.getByRole('cell', { name: 'swe-bench-lite' })).toBeVisible()
  await page.getByRole('link', { name: 'Jobs' }).click()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  await expect(page.getByRole('dialog', { name: 'Selected job' })).toBeVisible()
  await expect(page.getByText('Job trials')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'System doctor' })).toHaveCount(0)
})

test('launch action creates a queued draft job', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Run job' }).click()
  await expect(page).toHaveURL(/#jobs\/new$/)
  await expect(page.getByRole('link', { name: 'Jobs' })).toHaveClass(/active/)
  await expect(page.getByRole('navigation', { name: 'Job creation path' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Job creation path' }).getByRole('button', { name: 'Jobs' }).click()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await page.getByRole('button', { name: 'Run job' }).click()
  await expect(page.getByRole('heading', { name: 'New Job' })).toBeVisible()
  await expect(page.getByLabel('job_name')).toHaveValue('terminal-bench-smoke')
  await expect(page.getByLabel('include_task_name')).toHaveValue('apt-*')
  await expect(page.getByLabel('debug')).toContainText('disabled')
  await expect(page.getByLabel('yes')).toContainText('enabled')
  await expect(page.getByLabel('env_file')).toHaveValue('.env.harbor')
  await expect(page.getByLabel('agent env')).toHaveCount(0)
  await page.getByRole('tab', { name: 'Agent' }).click()
  await expect(page.getByLabel('agent env')).toHaveValue('ANTHROPIC_API_KEY')
  await expect(page.getByLabel('allow_agent_host')).toHaveValue('api.anthropic.com,hub.harborframework.com')
  await page.getByRole('tab', { name: 'Environment' }).click()
  await expect(page.getByLabel('environment env')).toHaveValue('HTTP_PROXY=')
  await page.getByRole('tab', { name: 'Verifier' }).click()
  await expect(page.getByLabel('verifier env')).toHaveValue('PYTEST_ADDOPTS=-q')
  await page.getByRole('tab', { name: 'Runtime' }).click()
  await expect(page.getByLabel('retry wait multiplier')).toHaveValue('1.5')
  await page.getByRole('tab', { name: 'Hub & Artifacts' }).click()
  await expect(page.getByRole('heading', { name: 'Job plugins' })).toBeVisible()
  await expect(page.getByText('No installed harbor.plugins entry point plugins detected.')).toBeVisible()
  await expect(page.getByLabel('plugin import_path')).toHaveValue('harbor.plugins.cost:CostPlugin')
  await expect(page.getByText(/--include-task-name apt-\*/)).toBeVisible()
  await expect(page.getByText(/--env-file \.env\.harbor/)).toBeVisible()
  await page.locator('#new-job').getByRole('button', { name: 'Run job' }).click()
  await expect(page.getByRole('button', { name: 'terminal-bench-draft' })).toBeVisible()
})

test('nests task and trial concepts while toggling preferences', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Hub connected' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Login' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Logout' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Tasks' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Trials' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('cell', { name: 'terminal-bench', exact: true }).click()
  await expect(page.getByText('Dataset tasks')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'Jobs' }).click()
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  await expect(page.getByText('Job trials')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'System' }).click()
  await expect(page.getByRole('heading', { name: 'System health' })).toBeVisible()
  await page.getByLabel('Language').click()
  await page.getByRole('option', { name: '中' }).click()
  await expect(page.getByRole('heading', { name: '系统健康' })).toBeVisible()
  await page.getByRole('button', { name: '深色' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})

test('manages agents and dataset scoped leaderboard surfaces', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Agents' }).click()
  await expect(page.getByRole('heading', { name: 'Agent catalog' })).toBeVisible()
  await expect(page.getByText('claude-code')).toBeVisible()
  await expect(page.getByText('local-repair-agent')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Selected agent' })).toHaveCount(0)
  await page.getByText('local-repair-agent').click()
  await expect(page.getByRole('dialog', { name: 'Selected agent' })).toBeVisible()
  await expect(page.getByText('env readiness')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Adapter init' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Adapter review' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Validate' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Compile' })).toHaveCount(0)
  await expect(page.getByText('extra_allowed_hosts: localhost, model.internal')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()

  await page.getByRole('link', { name: 'Leaderboard' }).click()
  await expect(page.getByRole('heading', { name: 'Leaderboard' })).toBeVisible()
  await expect(page.getByText('Metric')).toBeVisible()
  await expect(page.getByText('Submission')).toBeVisible()
  await expect(page.getByLabel('Agent filter')).toBeVisible()
  await expect(page.getByText('Reproducibility')).toBeVisible()
  await expect(page.getByLabel('Select dataset')).toContainText('terminal-bench@2.0')
  await expect(page.getByText('job_91a7', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Submit' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open report' })).toHaveCount(0)
  await page.getByLabel('Search datasets').fill('swe')
  await page.getByLabel('Select dataset').click()
  await page.getByRole('option', { name: 'swe-bench-lite@2026.06' }).click()
  await expect(page.getByText('job_74c1', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Search leaderboard')).toHaveCount(0)
  await expect(page.getByText('claude-sonnet-4-5')).toBeVisible()
  await expect(page.getByText('gpt-5.1')).toBeVisible()
})

test('shows system maintenance operations', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'System' }).click()
  await expect(page.getByRole('heading', { name: 'System health' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'System checks' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'System actions' })).toHaveCount(0)
  await expect(page.getByText('Interrupted runs reconciled')).toHaveCount(0)
  await expect(page.getByText('Harbor cache command available')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Cache' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Hub connected' })).toBeVisible()
  await expect(page.getByText('Authentication')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Status', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Login' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Logout' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Clean cache' })).toBeVisible()
  await page.getByRole('button', { name: 'Clean cache' }).click()
  await expect(page.getByRole('dialog', { name: 'Cleanup scope' })).toBeVisible()
  await expect(page.getByLabel('Clean all (Docker + ~/.cache/harbor)')).toBeChecked()
  await expect(page.getByText(/harbor cache clean/)).toHaveCount(0)
  await page.getByLabel('Clean Docker only').check()
  await expect(page.getByLabel('Clean all (Docker + ~/.cache/harbor)')).not.toBeChecked()
  await expect(page.getByLabel('Clean Docker only')).toBeChecked()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('dialog', { name: 'Cleanup scope' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Plugins' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Sync' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upload' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Submit' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Share' })).toHaveCount(0)
  await expect(page.getByText(/harbor auth/)).toHaveCount(0)
})
