import { expect, test } from '@playwright/test'

test('renders primary Harbor WebUI demo surfaces', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('link', { name: /OrnnLab/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Jobs' })).toHaveClass(/active/)
  await expect(page.getByRole('columnheader', { name: 'Updated' })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: 'Token usage (M)' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Runtime duration' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Created time' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '72.5%' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '87/100' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '0.72' })).toHaveCount(0)
  await expect(page.getByRole('cell', { name: '0.0184M' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '00:42:18' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '2026-06-29 03:46:12' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Selected job' })).toHaveCount(0)
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  const jobDialog = page.getByRole('dialog', { name: 'Selected job' })
  await expect(jobDialog).toBeVisible()
  await expect(jobDialog.getByText('Selected job')).toHaveCount(0)
  await expect(page.getByText('Job trials')).toBeVisible()
  await expect(page.getByText('Hub actions')).toHaveCount(0)
  await expect(jobDialog.getByRole('button', { name: 'Pause' })).toBeVisible()
  await expect(jobDialog.getByRole('checkbox', { name: 'Include in leaderboard' })).toBeChecked()
  await expect(page.getByRole('button', { name: 'Open viewer' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Upload' })).toBeVisible()
  await expect(jobDialog.getByRole('button', { name: 'Download' })).toHaveCount(0)
  await expect(page.getByText('/Users/xuzhang/.ornnlab/HarnessLab/jobs/terminal-bench-smoke/harbor.capability.json')).toBeVisible()
  await expect(page.getByText('/Users/xuzhang/.ornnlab/HarnessLab/trials/job_91a7')).toBeVisible()
  await expect(page.getByText('Trial diagnostics')).toHaveCount(0)
  await expect(page.getByText('analysis: trials/job_91a7/apt-setup.analysis.json')).toHaveCount(0)
  await page.getByRole('button', { name: /apt-setup/i }).click()
  await expect(page.getByText('retries: 0')).toBeVisible()
  await expect(page.getByText('log path: trials/job_91a7/apt-setup.log')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'Datasets' }).click()
  await expect(page.getByRole('heading', { name: 'Dataset catalog' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Datasets' })).toHaveClass(/active/)
  const datasetsTable = page.getByRole('table')
  await expect(datasetsTable.getByRole('columnheader', { name: 'Digest' })).toHaveCount(0)
  await expect(datasetsTable.getByRole('columnheader', { name: 'Updated' })).toHaveCount(0)
  await expect(datasetsTable.getByRole('columnheader', { name: 'Path' })).toBeVisible()
  await expect(datasetsTable.getByRole('columnheader', { name: 'Size' })).toBeVisible()
  await expect(datasetsTable.getByRole('columnheader', { name: 'Actions' })).toBeVisible()
  await expect(datasetsTable.getByText('~/.cache/harbor/datasets/terminal-bench')).toBeVisible()
  await expect(datasetsTable.getByText('1.2 GB')).toBeVisible()
  const sweRow = page.getByRole('row', { name: /swe-bench-lite/ })
  await sweRow.getByRole('button', { name: 'Download' }).click()
  await expect(page.getByRole('dialog', { name: 'Selected dataset' })).toHaveCount(0)
  await expect(sweRow.getByText('0%')).toBeVisible()
  await sweRow.getByRole('button', { name: 'Cancel download' }).click()
  await expect(sweRow.getByText('Not downloaded').first()).toBeVisible()
  const terminalRow = page.getByRole('row', { name: /terminal-bench 2.0/ })
  await terminalRow.getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByRole('dialog', { name: 'Delete local dataset' })).toBeVisible()
  await expect(page.getByText('This removes the downloaded dataset files from local storage.')).toBeVisible()
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(terminalRow.getByText('Not downloaded').first()).toBeVisible()
  await expect(page.getByRole('cell', { name: 'terminal-bench', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Selected dataset' })).toHaveCount(0)
  await page.getByRole('cell', { name: 'terminal-bench', exact: true }).click()
  const datasetDialog = page.getByRole('dialog', { name: 'Selected dataset' })
  await expect(datasetDialog).toBeVisible()
  await expect(datasetDialog.getByText('Selected dataset')).toHaveCount(0)
  await expect(page.getByText('Dataset tasks')).toBeVisible()
  await expect(datasetDialog.getByText('Splits', { exact: true })).toHaveCount(0)
  await expect(datasetDialog.getByLabel('Split')).toContainText('All splits')
  await expect(datasetDialog.getByText('Registry', { exact: true })).toBeVisible()
  await expect(page.getByText('registry_url')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Run single task' }).first()).toBeVisible()
  await datasetDialog.getByLabel('Split').click()
  await page.getByRole('option', { name: 'nightly' }).click()
  await expect(datasetDialog.getByText('sqlite-log-repair')).toBeVisible()
  await expect(datasetDialog.getByText('apt-setup')).toHaveCount(0)
  await datasetDialog.getByLabel('Split').click()
  await page.getByRole('option', { name: 'All splits' }).click()
  await page.getByLabel('Search tasks').fill('sqlite')
  await expect(datasetDialog.getByText('sqlite-log-repair')).toBeVisible()
  await expect(datasetDialog.getByText('apt-setup')).toHaveCount(0)
  await page.getByLabel('Search tasks').fill('')
  await expect(datasetDialog.getByText('apt-setup')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start environment' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Debug' })).toHaveCount(0)
  await expect(page.getByText('Manifest tools')).toHaveCount(0)
  await expect(page.getByText(/harbor init/)).toHaveCount(0)
  await expect(page.getByText('Task config')).toHaveCount(0)
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByLabel('Search datasets').fill('swe')
  await expect(page.getByRole('cell', { name: 'swe-bench-lite' })).toBeVisible()
  await page.getByRole('link', { name: 'Jobs' }).click()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  await expect(page.getByRole('dialog', { name: 'Selected job' })).toBeVisible()
  await expect(page.getByText('Job trials')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'System doctor' })).toHaveCount(0)
})

test('launch action creates a queued draft job', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('header').getByRole('button', { name: 'Run job' })).toHaveCount(0)
  await page.getByRole('button', { name: 'New Job' }).click()
  await expect(page).toHaveURL(/#jobs\/new$/)
  await expect(page.getByRole('link', { name: 'Jobs' })).toHaveClass(/active/)
  await expect(page.getByRole('navigation', { name: 'Job creation path' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Job creation path' }).getByRole('button', { name: 'Jobs' }).click()
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await page.getByRole('button', { name: 'New Job' }).click()
  await expect(page.getByRole('heading', { name: 'New Job' })).toBeVisible()
  await expect(page.locator('#new-job').getByRole('button', { name: 'Cancel' })).toBeVisible()
  await page.locator('#new-job').getByRole('button', { name: 'Cancel' }).click()
  await expect(page).toHaveURL(/#jobs$/)
  await expect(page.getByRole('heading', { name: 'Job registry' })).toBeVisible()
  await page.getByRole('button', { name: 'New Job' }).click()
  await expect(page.getByRole('heading', { name: 'New Job' })).toBeVisible()
  await expect(page.getByLabel('job_name')).toHaveValue('terminal-bench-smoke')
  await expect(page.getByRole('button', { name: 'Choose folder' })).toBeVisible()
  await expect(page.getByLabel('Model')).toHaveCount(0)
  await expect(page.getByLabel('Environment')).toContainText('Docker default')
  await expect(page.getByLabel('Debug mode')).toContainText('Disabled')
  await expect(page.getByLabel('env_file')).toHaveCount(0)
  await expect(page.getByLabel('Dataset').locator('..')).toHaveCSS('border-top-width', '1px')
  await expect(page.getByLabel('Include in leaderboard')).toContainText('Enabled')
  await expect(page.getByLabel('Notes')).toHaveValue('')
  await expect(page.getByLabel('Split')).toHaveCount(0)
  await page.getByRole('tab', { name: 'Tasks' }).click()
  await expect(page.getByLabel('Split')).toContainText('test')
  await expect(page.getByRole('region', { name: 'Task whitelist' })).toContainText('Selected tasks: 4 / 4')
  await expect(page.getByLabel(/apt-setup/)).toBeChecked()
  await page.getByLabel('Search tasks').fill('sqlite')
  await expect(page.getByLabel('extra_instruction_paths')).toHaveValue('instructions/hardening.md')
  await expect(page.getByText('sqlite-log-repair')).toBeVisible()
  await expect(page.getByText('apt-setup')).toHaveCount(0)
  await page.getByRole('button', { name: 'Disable all' }).click()
  await expect(page.getByRole('region', { name: 'Task whitelist' })).toContainText('Selected tasks: 3 / 4')
  await expect(page.getByLabel(/sqlite-log-repair/)).not.toBeChecked()
  await page.getByRole('button', { name: 'Enable all' }).click()
  await expect(page.getByRole('region', { name: 'Task whitelist' })).toContainText('Selected tasks: 4 / 4')
  await page.getByLabel('Search tasks').fill('')
  await page.getByLabel(/apt-setup/).click()
  await expect(page.getByRole('region', { name: 'Task whitelist' })).toContainText('Selected tasks: 3 / 4')
  await expect(page.getByLabel('agent env')).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Environment' })).toHaveCount(0)
  await page.getByRole('tab', { name: 'Verifier' }).click()
  await expect(page.getByLabel('Verifier mode')).toContainText('Use Dataset default verifier')
  await expect(page.getByLabel('verifier env')).toHaveCount(0)
  await page.getByLabel('Verifier mode').click()
  await page.getByRole('option', { name: 'Custom verifier' }).click()
  await expect(page.getByLabel('verifier import_path')).toHaveValue('')
  await expect(page.getByText('verifier env')).toBeVisible()
  await page.getByLabel('Verifier mode').click()
  await page.getByRole('option', { name: 'Skip verification' }).click()
  await page.getByRole('tab', { name: 'Basic' }).click()
  await expect(page.getByLabel('Include in leaderboard')).toContainText('Disabled')
  await expect(page.getByLabel('Include in leaderboard')).toBeDisabled()
  await page.getByRole('tab', { name: 'Verifier' }).click()
  await page.getByLabel('Verifier mode').click()
  await page.getByRole('option', { name: 'Use Dataset default verifier' }).click()
  await page.getByRole('tab', { name: 'Basic' }).click()
  await expect(page.getByLabel('Include in leaderboard')).toContainText('Disabled')
  await expect(page.getByLabel('Include in leaderboard')).toBeEnabled()
  await page.getByRole('tab', { name: 'Runtime' }).click()
  await expect(page.getByLabel('Timeout policy')).toContainText('Standard (1x)')
  await expect(page.getByLabel('Enable failure retry')).not.toBeChecked()
  await expect(page.getByLabel('Failure retries')).toHaveCount(0)
  await expect(page.getByLabel('Retry interval')).toHaveCount(0)
  await page.getByLabel('Enable failure retry').check()
  await expect(page.getByLabel('Failure retries')).toHaveValue('1')
  await expect(page.getByLabel('Retry interval')).toContainText('Standard (starts at 2s, max 30s)')
  await expect(page.getByLabel('Task execution timeout')).toBeChecked()
  await expect(page.getByLabel('quiet')).toHaveCount(0)
  await expect(page.getByLabel('retry wait multiplier')).toHaveCount(0)
  await page.getByLabel('Timeout policy').click()
  await page.getByRole('option', { name: 'Custom multiplier' }).click()
  await expect(page.getByLabel('Timeout policy')).toContainText('Custom multiplier')
  await expect(page.getByLabel('Overall timeout multiplier')).toHaveValue('1')
  await page.getByLabel('Retry interval').click()
  await page.getByRole('option', { name: 'Custom interval' }).click()
  await expect(page.getByLabel('Retry interval')).toContainText('Custom interval')
  await expect(page.getByLabel('Wait growth multiplier')).toHaveValue('1.5')
  await expect(page.getByLabel('Agent setup timeout multiplier')).toHaveCount(0)
  await page.getByRole('button', { name: 'Expand advanced parameters' }).click()
  await expect(page.getByLabel('Agent setup timeout multiplier')).toHaveValue('1')
  await expect(page.getByLabel('Environment build timeout multiplier')).toHaveValue('1')
  await expect(page.getByLabel('Raw errors that should not retry (match rule) 1')).toHaveValue('ValidationError')
  await page.getByRole('button', { name: 'Add' }).click()
  await expect(page.getByLabel('Raw errors that should not retry (match rule) 2')).toHaveValue('')
  await page.getByRole('button', { name: 'Delete' }).last().click()
  await expect(page.getByLabel('Raw errors that should not retry (match rule) 2')).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Output' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Artifacts' })).toHaveCount(0)
  await expect(page.getByLabel('artifacts 1')).toHaveCount(0)
  await expect(page.getByLabel('plugin import_path')).toHaveCount(0)
  await expect(page.getByLabel('Visibility')).toHaveCount(0)
  await expect(page.getByLabel('upload to Hub')).toHaveCount(0)
  await expect(page.getByLabel('metric')).toHaveCount(0)
  await expect(page.getByText('No installed harbor.plugins entry point plugins detected.')).toHaveCount(0)
  await expect(page.getByText(/harbor run/)).toHaveCount(0)
  await page.locator('#new-job').getByRole('button', { name: 'Run job' }).click()
  await expect(page.getByRole('button', { name: 'terminal-bench-draft' })).toBeVisible()
})

test('nests task and trial concepts while toggling preferences', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Hub connected' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Login' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Logout' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Tasks' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Trials' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('cell', { name: 'terminal-bench', exact: true }).click()
  await expect(page.getByText('Dataset tasks')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'Jobs' }).click()
  await page.getByRole('button', { name: 'terminal-bench-smoke' }).click()
  await expect(page.getByText('Job trials')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await page.getByRole('link', { name: 'System' }).click()
  await expect(page.getByRole('heading', { name: 'System health' })).toBeVisible()
  await page.getByLabel('Language').click()
  await page.getByRole('option', { name: '中' }).click()
  await expect(page.getByRole('heading', { name: '系统健康' })).toBeVisible()
  await page.getByRole('button', { name: '深色' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})

test('manages agents and dataset scoped leaderboard surfaces', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Agents' }).click()
  await expect(page.getByRole('heading', { name: 'Agent catalog' })).toBeVisible()
  await expect(page.getByLabel('Search agents')).toBeVisible()
  await expect(page.getByRole('button', { name: 'New Agent' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Agent Name' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Harness' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Actions' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Adapter' })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: 'Source' })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: 'Updated' })).toHaveCount(0)
  await expect(page.getByText('Claude Code default')).toBeVisible()
  await expect(page.getByText('claude-code')).toBeVisible()
  await expect(page.getByText('Local repair agent')).toBeVisible()
  await expect(page.getByText('custom-harness')).toBeVisible()
  const builtinAgentRow = page.getByRole('row', { name: /Claude Code default/ })
  await expect(builtinAgentRow.getByRole('button', { name: 'Delete' })).toHaveCount(0)
  const customAgentRow = page.getByRole('row', { name: /Local repair agent/ })
  await customAgentRow.getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByRole('dialog', { name: 'Delete custom agent' })).toBeVisible()
  await expect(page.getByText('This removes the custom agent configuration from the local WebUI list.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.getByLabel('Search agents').fill('local')
  await expect(page.getByText('Local repair agent')).toBeVisible()
  await expect(page.getByText('claude-code')).toHaveCount(0)
  await page.getByLabel('Search agents').fill('')
  await expect(page.getByRole('dialog', { name: 'Selected agent' })).toHaveCount(0)
  await page.getByText('Local repair agent').click()
  const agentDialog = page.getByRole('dialog', { name: 'Selected agent' })
  await expect(agentDialog).toBeVisible()
  await expect(agentDialog.getByText('Selected agent')).toHaveCount(0)
  await expect(page.getByText('custom-harness').first()).toBeVisible()
  await expect(page.getByText('Credentials and parameters')).toBeVisible()
  await expect(page.getByText('Capability config')).toHaveCount(0)
  await expect(page.getByText('Config check')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Check config' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Adapter init' })).toHaveCount(0)
  await expect(page.getByText(/harbor adapter/)).toHaveCount(0)
  await page.getByRole('tab', { name: 'Advanced' }).click()
  await expect(page.getByText('Advanced agent params')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await customAgentRow.getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page.getByText('Local repair agent')).toHaveCount(0)

  await page.getByRole('link', { name: 'Environment' }).click()
  await expect(page.getByRole('heading', { name: 'Environment catalog' })).toBeVisible()
  await expect(page.getByLabel('Search environments')).toBeVisible()
  await expect(page.getByText('Docker default')).toBeVisible()
  await expect(page.getByText('Docker GPU')).toBeVisible()
  await page.getByText('Docker GPU').click()
  const environmentDialog = page.getByRole('dialog', { name: 'Selected environment' })
  await expect(environmentDialog).toBeVisible()
  await expect(page.getByText('nvidia/cuda:12.4-runtime')).toBeVisible()
  const firstEnvironmentGroup = environmentDialog.locator('.environment-editor .run-config-group').first()
  const closedGroupHeight = await firstEnvironmentGroup.evaluate((element) => element.getBoundingClientRect().height)
  await environmentDialog.getByRole('button', { name: 'Type', exact: true }).click()
  const openGroupHeight = await firstEnvironmentGroup.evaluate((element) => element.getBoundingClientRect().height)
  expect(Math.abs(openGroupHeight - closedGroupHeight)).toBeLessThanOrEqual(2)
  await expect(environmentDialog.locator('[role="listbox"][aria-label="Type options"]')).toBeVisible()
  expect(await environmentDialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.keyboard.press('Escape')
  await environmentDialog.evaluate((element) => {
    element.scrollTop = element.scrollHeight
  })
  const widthBeforeResize = await environmentDialog.evaluate((element) => element.getBoundingClientRect().width)
  const resizeHandle = page.getByRole('separator', { name: 'Resize detail drawer' })
  const handleBox = await resizeHandle.boundingBox()
  const viewportHeight = await page.evaluate(() => window.innerHeight)
  const maxDrawerWidth = await page.evaluate(() => window.innerWidth - 32)
  expect(handleBox?.height).toBeGreaterThanOrEqual(viewportHeight - 2)
  if (!handleBox) throw new Error('missing resize handle bounds')
  if (widthBeforeResize < maxDrawerWidth - 2) {
    await page.mouse.move(handleBox.x + 5, viewportHeight - 24)
    await page.mouse.down()
    await page.mouse.move(handleBox.x - 75, viewportHeight - 24)
    await page.mouse.up()
    const widthAfterResize = await environmentDialog.evaluate((element) => element.getBoundingClientRect().width)
    expect(widthAfterResize).toBeGreaterThan(widthBeforeResize + 60)
  } else {
    expect(widthBeforeResize).toBeCloseTo(maxDrawerWidth, 0)
  }
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()

  await page.getByRole('link', { name: 'Leaderboard' }).click()
  await expect(page.getByRole('heading', { name: 'Leaderboard' })).toBeVisible()
  await expect(page.getByText('Metric')).toBeVisible()
  await expect(page.getByText('Submission')).toHaveCount(0)
  await expect(page.getByText('Uploaded URL')).toHaveCount(0)
  await expect(page.getByLabel('Agent filter')).toBeVisible()
  await expect(page.getByText('Reproducibility')).toHaveCount(0)
  await expect(page.getByLabel('Select dataset')).toContainText('terminal-bench@2.0')
  await expect(page.getByRole('columnheader', { name: 'Agent Name' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Harness' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Tokens (M)' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Actions' })).toBeVisible()
  await expect(page.getByText('Claude Code default')).toBeVisible()
  await expect(page.getByText('claude-code')).toBeVisible()
  await expect(page.getByText('0.0184M')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Submit' })).toHaveCount(0)
  await page.getByRole('button', { name: 'job_91a7' }).click()
  await expect(page.getByRole('dialog', { name: 'Selected job' })).toBeVisible()
  await expect(page.getByText('Job trials')).toBeVisible()
  await page.getByRole('button', { name: 'Close detail drawer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open report' })).toHaveCount(0)
  const firstRankRow = page.getByRole('row', { name: /job_91a7/ })
  await firstRankRow.getByRole('button', { name: 'Remove' }).click()
  await expect(page.getByText('job_91a7')).toHaveCount(0)
  await expect(page.getByRole('row', { name: /job_64f2/ })).toContainText('#1')
  await page.getByLabel('Search datasets').fill('swe')
  await page.getByLabel('Select dataset').click()
  await page.getByRole('option', { name: 'swe-bench-lite@2026.06' }).click()
  await expect(page.getByText('job_74c1', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Search leaderboard')).toHaveCount(0)
  await expect(page.getByText('claude-sonnet-4-5')).toBeVisible()
  await expect(page.getByText('gpt-5.1')).toBeVisible()
})

test('shows system maintenance operations', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'System' }).click()
  await expect(page.getByRole('heading', { name: 'System health' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'System checks' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'System actions' })).toHaveCount(0)
  await expect(page.getByText('Interrupted runs reconciled')).toHaveCount(0)
  await expect(page.getByText('Harbor cache command available')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Cache' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Hub connected' })).toBeVisible()
  await expect(page.getByText('Authentication')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Status', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Login' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Logout' })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: 'Actions' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Path' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Evidence' })).toHaveCount(0)
  await expect(page.getByText('OrnnLab Service')).toBeVisible()
  await expect(page.getByText('0.1.3 latest')).toBeVisible()
  await expect(page.getByText('http://127.0.0.1:5173')).toBeVisible()
  await expect(page.getByRole('row', { name: 'CPU Usage Running 12% system monitor: cpu' })).toBeVisible()
  await expect(page.getByRole('row', { name: 'GPU Usage Running 0% system monitor: gpu' })).toBeVisible()
  await expect(page.getByRole('row', { name: 'Available Storage Healthy 48Gi available /Volumes/XU-1TB-NPM' })).toBeVisible()
  await expect(page.getByRole('row').nth(5)).toContainText('CPU Usage')
  await expect(page.getByRole('row').nth(6)).toContainText('GPU Usage')
  await expect(page.getByRole('row').nth(7)).toContainText('Available Storage')
  await expect(page.getByText('Local cache')).toHaveCount(0)
  await expect(page.getByText('0.01 MB cache')).toBeVisible()
  await expect(page.getByText('~/.cache/harbor')).toBeVisible()
  await expect(page.getByText('docker context: colima')).toBeVisible()
  await expect(page.getByRole('row', { name: 'OrnnLab Service Running 0.1.3 latest http://127.0.0.1:5173 Check update Restart' })).toBeVisible()
  await page.getByRole('row', { name: 'OrnnLab Service Running 0.1.3 latest http://127.0.0.1:5173 Check update Restart' }).getByRole('button', { name: 'Check update' }).click()
  await expect(page.getByRole('status')).toContainText('OrnnLab is already on the latest npm version.')
  await expect(page.getByRole('status')).toContainText('3s')
  await page.getByRole('button', { name: 'Dismiss' }).click()
  await page.getByRole('row', { name: 'OrnnLab Service Running 0.1.3 latest http://127.0.0.1:5173 Check update Restart' }).getByRole('button', { name: 'Restart' }).click()
  await expect(page.getByRole('dialog', { name: 'Restart OrnnLab service' })).toBeVisible()
  await expect(page.getByText('This forces the OrnnLab frontend and backend services to restart.')).toHaveCount(0)
  await expect(page.getByText('The WebUI may disconnect briefly and reload after the frontend service comes back.')).toBeVisible()
  await expect(page.getByText('Active Harbor orchestration requests may be interrupted while the backend restarts.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('dialog', { name: 'Restart OrnnLab service' })).toHaveCount(0)
  await expect(page.getByRole('row', { name: 'Docker Running context colima docker context: colima Clean cache' })).toBeVisible()
  await page.getByRole('row', { name: 'Docker Running context colima docker context: colima Clean cache' }).getByRole('button', { name: 'Clean cache' }).click()
  await expect(page.getByRole('dialog', { name: 'Clean Docker cache' })).toBeVisible()
  await expect(page.getByText('This removes Harbor-matched Docker images only.')).toHaveCount(0)
  await expect(page.getByText('Future jobs may need to rebuild or pull images again, increasing startup time.')).toBeVisible()
  await expect(page.getByText(/harbor cache clean/)).toHaveCount(0)
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('dialog', { name: 'Clean Docker cache' })).toHaveCount(0)
  await page.getByRole('row', { name: 'Storage Completed 0.01 MB cache ~/.cache/harbor Clean cache' }).getByRole('button', { name: 'Clean cache' }).click()
  await expect(page.getByRole('dialog', { name: 'Clean local cache' })).toBeVisible()
  await expect(page.getByText('This removes Harbor local cache data only.')).toHaveCount(0)
  await expect(page.getByText('Deletes the local Harbor cache directory at ~/.cache/harbor.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Plugins' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Sync' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upload' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Submit' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Share' })).toHaveCount(0)
  await expect(page.getByText(/harbor auth/)).toHaveCount(0)
})
