import type { EnvironmentRow, RunDraft } from './harbor'

export const defaultRunDraft: RunDraft = {
  agent: 'Claude Code default',
  agentEnv: 'ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}',
  agentImportPath: 'harbor.adapters.claude_code',
  agentKwargs: 'temperature=0',
  agentSetupTimeoutMultiplier: '1',
  agentTimeoutMultiplier: '1',
  allowAgentHosts: 'api.anthropic.com',
  allowEnvironmentHosts: 'pypi.org, github.com',
  attempts: 1,
  concurrency: 4,
  cpuOverride: 'none',
  cpus: 'task default',
  debug: false,
  deleteEnvironment: true,
  disableVerifier: false,
  dockerCompose: 'none',
  environment: 'docker-default',
  environmentBuildTimeoutMultiplier: '1',
  environmentEnv: 'HTTP_PROXY=${HTTP_PROXY:-}',
  environmentImportPath: 'none',
  environmentKwargs: 'none',
  extraInstructions: '',
  forceBuild: false,
  gpus: 'none',
  includeInLeaderboard: true,
  jobsDir: 'jobs/terminal-bench-smoke',
  jobName: 'terminal-bench-smoke',
  maxRetries: 0,
  memoryMb: 'task default',
  metric: 'pass@1 mean',
  mcpConfig: 'none',
  model: 'anthropic/claude-haiku-4-5',
  mounts: '[{"type":"bind","source":"./cache","target":"/cache"}]',
  notes: '',
  retryExclude: '',
  retryInclude: 'TimeoutError',
  retryIntervalPolicy: 'standard',
  retryMaxWaitSec: '30',
  retryMinWaitSec: '2',
  retryWaitMultiplier: '1.5',
  selectedTaskNames: null,
  skills: '~/.ornnlab/skills/terminal-bench',
  source: 'terminal-bench@2.0',
  split: 'test',
  storageMb: 'task default',
  suppressOverrideWarnings: false,
  timeoutMultiplier: 1,
  timeoutPolicy: 'standard',
  tpu: 'none',
  verifierEnv: 'none',
  verifierImportPath: 'none',
  verifierKwargs: 'none',
  verifierMaxTimeoutSec: 'task default',
  verifierMode: 'dataset-default',
  verifierTimeoutMultiplier: '1',
}

export const defaultEnvironmentDraft: EnvironmentRow = {
  allowedHosts: '*',
  cpuPolicy: 'auto',
  cpus: '',
  deleteAfterRun: false,
  dockerCompose: 'none',
  dockerImage: '',
  env: 'none',
  environmentType: 'docker',
  extraAllowedHosts: 'none',
  forceBuild: false,
  gpus: '0',
  gpuTypes: '',
  healthcheck: '',
  id: 'custom-environment',
  importPath: 'none',
  kwargs: 'none',
  memoryMb: '',
  memoryPolicy: 'auto',
  mounts: 'none',
  name: 'Custom Environment',
  networkMode: 'public',
  os: 'linux',
  overrideCpus: '',
  overrideGpus: '',
  overrideMemoryMb: '',
  overrideStorageMb: '',
  overrideTpu: '',
  profileType: 'custom',
  skillsDir: 'none',
  storageMb: '',
  tpu: 'none',
  workdir: '',
}
