import type { EnvironmentRow, RunDraft } from './harbor'

export const defaultRunDraft: RunDraft = {
  agent: 'Local repair agent',
  agentSetupTimeoutMultiplier: '1',
  agentTimeoutMultiplier: '1',
  attempts: 1,
  concurrency: 4,
  debug: false,
  environment: 'docker-default',
  environmentBuildTimeoutMultiplier: '1',
  extraInstructions: '',
  includeInLeaderboard: true,
  jobsDir: 'jobs/terminal-bench-smoke',
  jobName: 'terminal-bench-smoke',
  maxRetries: 0,
  metric: 'mean',
  notes: '',
  retryExclude: '',
  retryInclude: 'TimeoutError',
  retryIntervalPolicy: 'standard',
  retryMaxWaitSec: '30',
  retryMinWaitSec: '2',
  retryWaitMultiplier: '1.5',
  selectedTaskNames: null,
  source: 'terminal-bench@2.0',
  timeoutMultiplier: 1,
  timeoutPolicy: 'standard',
  verifierMode: 'dataset-default',
  verifierTimeoutMultiplier: '1',
}

export const defaultEnvironmentDraft: EnvironmentRow = {
  allowedHosts: '*',
  cpuPolicy: 'auto',
  deleteAfterRun: false,
  dockerCompose: 'none',
  env: 'none',
  environmentType: 'docker',
  forceBuild: false,
  id: 'custom-environment',
  importPath: 'none',
  kwargs: 'none',
  memoryPolicy: 'auto',
  mounts: 'none',
  name: 'Custom Environment',
  overrideCpus: '',
  overrideGpus: '',
  overrideMemoryMb: '',
  overrideStorageMb: '',
  overrideTpu: '',
  profileType: 'custom',
}
